repos:
  - repo: https://github.com/docker-compose-linter/pre-commit-dclint
    rev: v3.1.0
    hooks:
      - id: dclint
        files: ^(docker-)?compose.*\.ya?ml$
        args: [--fix] # auto-apply fixes on commit
