#!/usr/bin/env bash
# tune.sh — Compute MySQL tuning values from CPUS / MEMORY in .env and write
#            mysql-tuning.cnf so docker compose can mount it as a config file.
#
# Usage:
#   ./tune.sh          # reads .env, writes mysql-tuning.cnf
set -e

# ── Load environment variables ────────────────────────────────────────────────
if [ ! -f .env ]; then
    echo "ERROR: .env file not found. Copy .env.example to .env and fill in your values." >&2
    exit 1
fi
# shellcheck source=.env.example
source .env

# ── Auto-derive MySQL tuning from CPUS / MEMORY ───────────────────────────────

# Parse MEMORY into total megabytes (awk handles the arithmetic; bash is int-only)
mem_unit="${MEMORY: -1}"
mem_num="${MEMORY%[GMgm]}"
case "${mem_unit^^}" in
    G) MEM_MB=$(awk "BEGIN{printf \"%d\", ${mem_num} * 1024}") ;;
    M) MEM_MB=${mem_num} ;;
    *) echo "ERROR: MEMORY must end in G or M (e.g. 32G, 16384M)" >&2; exit 1 ;;
esac

# Round CPUS to nearest integer (supports decimal input e.g. 4.5)
CPU_INT=$(awk "BEGIN{printf \"%d\", ${CPUS} + 0.5}")

# buffer pool ≈ 65% of RAM, in whole GB — the single most important InnoDB knob
BP_GB=$(awk "BEGIN{printf \"%d\", ${MEM_MB} * 0.65 / 1024}")
INNODB_BUFFER_POOL_SIZE="${BP_GB}G"

# 1 instance per CPU, clamped to [1, 64] (MySQL hard limit)
INNODB_BUFFER_POOL_INSTANCES=$(( CPU_INT < 1 ? 1 : (CPU_INT > 64 ? 64 : CPU_INT) ))

# IO threads aligned to CPU count (same clamp as instances)
INNODB_READ_IO_THREADS=${INNODB_BUFFER_POOL_INSTANCES}
INNODB_WRITE_IO_THREADS=${INNODB_BUFFER_POOL_INSTANCES}

# Purge threads ≈ half of CPUs, minimum 1
INNODB_PURGE_THREADS=$(( CPU_INT / 2 < 1 ? 1 : CPU_INT / 2 ))

# Redo log capacity ≈ 20% of buffer pool, minimum 1G, in whole GB
# (replaces innodb_log_file_size in MySQL 8.0.30+)
REDO_GB=$(awk "BEGIN{v=int(${BP_GB} * 0.20); print (v < 1 ? 1 : v)}")
INNODB_REDO_LOG_CAPACITY="${REDO_GB}G"

# Log buffer ≈ 0.8% of RAM, clamped to [16M, 256M]
LOG_BUF_MB=$(awk "BEGIN{v=int(${MEM_MB} * 0.008); if(v<16)v=16; if(v>256)v=256; print v}")
INNODB_LOG_BUFFER_SIZE="${LOG_BUF_MB}M"

# ── Print summary ─────────────────────────────────────────────────────────────
echo "Derived MySQL tuning for ${CPUS} CPUs / ${MEMORY} RAM:"
echo "  innodb_buffer_pool_size      = ${INNODB_BUFFER_POOL_SIZE}"
echo "  innodb_buffer_pool_instances = ${INNODB_BUFFER_POOL_INSTANCES}"
echo "  innodb_read_io_threads       = ${INNODB_READ_IO_THREADS}"
echo "  innodb_write_io_threads      = ${INNODB_WRITE_IO_THREADS}"
echo "  innodb_purge_threads         = ${INNODB_PURGE_THREADS}"
echo "  innodb_redo_log_capacity     = ${INNODB_REDO_LOG_CAPACITY}"
echo "  innodb_log_buffer_size       = ${INNODB_LOG_BUFFER_SIZE}"

# ── Write mysql-tuning.cnf ────────────────────────────────────────────────────
cat > mysql-tuning.cnf <<EOF
# Auto-generated by tune.sh — do not edit by hand.
# Re-run ./tune.sh after changing CPUS or MEMORY in .env.
[mysqld]

# --- InnoDB buffer pool (most impactful knob) ---
innodb_buffer_pool_size        = ${INNODB_BUFFER_POOL_SIZE}
innodb_buffer_pool_instances   = ${INNODB_BUFFER_POOL_INSTANCES}

# --- IO threads ---
innodb_read_io_threads         = ${INNODB_READ_IO_THREADS}
innodb_write_io_threads        = ${INNODB_WRITE_IO_THREADS}
innodb_purge_threads           = ${INNODB_PURGE_THREADS}

# --- Redo log / log buffer ---
innodb_redo_log_capacity       = ${INNODB_REDO_LOG_CAPACITY}
innodb_log_buffer_size         = ${INNODB_LOG_BUFFER_SIZE}

# --- Flush strategy ---
# see: https://docs.netapp.com/us-en/ontap-apps-dbs/mysql/mysql-innodb_flush_log_at_trx_commit.html
innodb_flush_method            = O_DIRECT
innodb_flush_log_at_trx_commit = 2

# --- Per-connection buffers (kept modest; multiply per thread) ---
bulk_insert_buffer_size        = 256M
sort_buffer_size               = 64M
read_rnd_buffer_size           = 32M
join_buffer_size               = 32M

# --- Required for mysqlsh restore ---
local_infile                   = 1
EOF

echo "mysql-tuning.cnf written — ready to run: docker compose up -d"

